file=open("test.txt","w+")
file.write("Hey gentlman ")
file=open("test.txt","r")
print(file.read())
file=open("test.txt","a")
file.write("congratulation")
file=open("test.txt","r")
print(file.read())
file.close()
